# GET Request
GET http://localhost:3000/home
# POST Request with JSON data
POST http://localhost:3000/add
Content-Type: application/json

{
  "description": "Task from REST Client"
}

# PUT Request with JSON data
PUT http://localhost:3000/update/1
Content-Type: application/json

{
  "description": "Task from REST Client"
}

# DELETE Request
DELETE http://localhost:3000/delete/1
```